### ISSUE TITLE
implementing similar pattern with `Query` component

### ISSUE THREAD

**Issue by anthonychung14** [Drawbotics/react-apollo-redux#3]
This is a fantastic idea for teams transitioning to Apollo from Redux. (We're moving bits of our store into Apollo, but still need to keep consistency between the data store and the Apollo cache).

Any ideas on how to dispatch actions when the query returns data (or has errored)?

**Comment by larsbs** [comment]
Right now there's no supported way of doing that. This library is focused on mutations as we understand that the data that comes from GraphQL should stay in the apollo cache. Anyway, if you really need to put some data from the query into your redux store or do other things, you could easily do it in the `componentDidUpdate` method from the component fetching the data. Something like this:

```javascript
componentDidUpdate(prevProps) {
  const { loading, data } = this.props;
  const { loading: wasLoading } = prevProps;
  if ( ! loading && wasLoading) {
    // The component finished loading the data.
    // Do something with it (dispatch action, log it, etc.)
  }
}

**Comment by anthonychung14** [comment]
Nice this makes sense. I'm going to try implementing that logic in the `ReduxGraphQL` component (so we can have a queryWrapper instead of adding `componentDidUpdate` to everything.
